import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { CollaboratorList } from './CollaboratorList'
import { useAppStore } from '@/lib/app-store'
import type { Block, Editor, Grant } from '@/bindings'

// Mock child components
vi.mock('@/lib/tauri-client', () => ({
  TauriClient: {
    block: {
      checkPermission: vi.fn().mockResolvedValue(true),
    },
  },
}))

// Mock AddCollaboratorDialog
vi.mock('./AddCollaboratorDialog', () => ({
  AddCollaboratorDialog: ({ open, onSuccess }: any) =>
    open ? (
      <div data-testid="add-dialog">
        <button onClick={() => onSuccess({ editor_id: 'new-editor' })}>
          Mock Add
        </button>
      </div>
    ) : null,
}))

describe('CollaboratorList Component', () => {
  const mockGrantCapability = vi.fn()
  const mockRevokeCapability = vi.fn()
  const mockDeleteEditor = vi.fn()

  const mockBlock: Block = {
    block_id: 'block-1',
    name: 'Test Block',
    block_type: 'markdown',
    owner: 'owner-123',
    contents: {},
    children: {},
    metadata: {},
  }

  const mockOwnerEditor: Editor = {
    editor_id: 'owner-123',
    name: 'Owner',
    editor_type: 'Human',
  }

  const mockCollaboratorEditor: Editor = {
    editor_id: 'collab-456',
    name: 'Alice',
    editor_type: 'Human',
  }

  const mockGrants: Grant[] = [
    {
      editor_id: 'collab-456',
      cap_id: 'markdown.read',
      block_id: 'block-1',
    },
    {
      editor_id: 'collab-456',
      cap_id: 'markdown.write',
      block_id: 'block-1',
    },
  ]

  beforeEach(() => {
    vi.clearAllMocks()

    const store = useAppStore.getState()
    store.files = new Map([
      [
        'file-1',
        {
          fileId: 'file-1',
          metadata: null,
          activeEditorId: 'owner-123',
          editors: [mockOwnerEditor, mockCollaboratorEditor],
          blocks: [mockBlock],
          selectedBlockId: null,
          events: [],
          grants: mockGrants,
        },
      ],
    ])
    store.grantCapability = mockGrantCapability
    store.revokeCapability = mockRevokeCapability
    store.deleteEditor = mockDeleteEditor
    store.checkPermission = vi.fn().mockResolvedValue(true)
  })

  describe('Rendering', () => {
    it('should render collaborators list with owner and collaborators', () => {
      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      // Owner name appears twice (name + badge), so use getAllByText
      expect(screen.getAllByText('Owner').length).toBeGreaterThan(0)
      expect(screen.getByText('Alice')).toBeInTheDocument()
    })

    it('should show Add Collaborator button', async () => {
      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      // The button has a specific title when enabled
      const addButton = await screen.findByTitle('Add Collaborator')
      expect(addButton).toBeInTheDocument()
    })

    it('should only show editors with grants or owner', () => {
      const editorWithoutGrants: Editor = {
        editor_id: 'no-grants',
        name: 'NoAccess',
        editor_type: 'Human',
      }

      const store = useAppStore.getState()
      const fileState = store.files.get('file-1')
      if (fileState) {
        fileState.editors = [
          mockOwnerEditor,
          mockCollaboratorEditor,
          editorWithoutGrants,
        ]
      }

      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      expect(screen.getAllByText('Owner').length).toBeGreaterThan(0)
      expect(screen.getByText('Alice')).toBeInTheDocument()
      expect(screen.queryByText('NoAccess')).not.toBeInTheDocument()
    })
  })

  describe('Grant/Revoke Permissions', () => {
    it('should call revokeCapability when unchecking permission', async () => {
      mockRevokeCapability.mockResolvedValue(undefined)

      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      // Find Alice's read permission checkbox
      // We rely on the id pattern generated by CollaboratorItem: `${editorId}-${capId}`
      const readCheckbox = screen.getByTestId(
        'checkbox-collab-456-markdown.read'
      )

      // It should be checked initially (based on mockGrants)
      expect(readCheckbox).toHaveAttribute('aria-checked', 'true')

      // Click to uncheck
      await userEvent.click(readCheckbox)

      await waitFor(() => {
        expect(mockRevokeCapability).toHaveBeenCalledWith(
          'file-1',
          'collab-456',
          'markdown.read',
          'block-1'
        )
      })
    })
  })

  describe('Remove Access', () => {
    it('should revoke all capabilities when removing access via menu', async () => {
      mockRevokeCapability.mockResolvedValue(undefined)

      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      // 1. Open the dropdown menu for Alice
      // We need to find the specific trigger for Alice.
      // CollaboratorItem usually renders a "More options" button.
      const menuTrigger = screen.getByTestId('menu-trigger-collab-456')
      await userEvent.click(menuTrigger)

      // 2. Click "Remove Access" in the menu
      const removeButton = await screen.findByText('Remove Access')
      await userEvent.click(removeButton)

      await waitFor(() => {
        // Should revoke read and write capabilities
        expect(mockRevokeCapability).toHaveBeenCalledTimes(2)
        expect(mockRevokeCapability).toHaveBeenCalledWith(
          'file-1',
          'collab-456',
          'markdown.read',
          'block-1'
        )
        expect(mockRevokeCapability).toHaveBeenCalledWith(
          'file-1',
          'collab-456',
          'markdown.write',
          'block-1'
        )
      })

      // Should NOT delete editor
      expect(mockDeleteEditor).not.toHaveBeenCalled()
    })
  })

  describe('Add Collaborator', () => {
    it('should open dialog when Add Collaborator is clicked', async () => {
      const user = userEvent.setup()

      render(
        <CollaboratorList fileId="file-1" blockId="block-1" block={mockBlock} />
      )

      const addButton = await screen.findByTitle('Add Collaborator')
      await user.click(addButton)

      await waitFor(() => {
        expect(screen.getByTestId('add-dialog')).toBeInTheDocument()
      })
    })
  })

  describe('Agent Status Toggle', () => {
    const mockBotEditor: Editor = {
      editor_id: 'bot-789',
      name: 'ElfieeBot',
      editor_type: 'Bot',
    }

    const mockDirectoryBlock: Block = {
      block_id: 'dir-block-1',
      name: 'Project Dir',
      block_type: 'directory',
      owner: 'owner-123',
      contents: {},
      children: {},
      metadata: {},
    }

    const mockAgentBlock: Block = {
      block_id: 'agent-block-1',
      name: 'ElfieeBot Agent',
      block_type: 'agent',
      owner: 'owner-123',
      contents: {
        name: 'ElfieeBot',
        config_dir: '/home/user/repo/.claude',
        editor_id: 'bot-789',
        status: 'enabled',
      },
      children: {},
      metadata: {},
    }

    it('should render agent toggle for bot editor with matching agent block', () => {
      const store = useAppStore.getState()
      store.files = new Map([
        [
          'file-1',
          {
            fileId: 'file-1',
            metadata: null,
            activeEditorId: 'owner-123',
            editors: [mockOwnerEditor, mockBotEditor],
            blocks: [mockDirectoryBlock, mockAgentBlock],
            selectedBlockId: null,
            events: [],
            grants: [
              {
                editor_id: 'bot-789',
                cap_id: 'directory.read',
                block_id: 'dir-block-1',
              },
            ],
          },
        ],
      ])
      store.checkPermission = vi.fn().mockResolvedValue(true)
      store.grantCapability = vi.fn()
      store.revokeCapability = vi.fn()

      render(
        <CollaboratorList
          fileId="file-1"
          blockId="dir-block-1"
          block={mockDirectoryBlock}
        />
      )

      // The agent toggle should be rendered for the bot
      expect(screen.getByTestId('agent-toggle-bot-789')).toBeInTheDocument()
      expect(screen.getByText('Active')).toBeInTheDocument()
    })

    it('should render agent toggle OFF for bot editor without matching agent block', () => {
      const store = useAppStore.getState()
      store.files = new Map([
        [
          'file-1',
          {
            fileId: 'file-1',
            metadata: null,
            activeEditorId: 'owner-123',
            editors: [mockOwnerEditor, mockBotEditor],
            blocks: [mockDirectoryBlock], // No agent block
            selectedBlockId: null,
            events: [],
            grants: [
              {
                editor_id: 'bot-789',
                cap_id: 'directory.read',
                block_id: 'dir-block-1',
              },
            ],
          },
        ],
      ])
      store.checkPermission = vi.fn().mockResolvedValue(true)
      store.grantCapability = vi.fn()
      store.revokeCapability = vi.fn()

      render(
        <CollaboratorList
          fileId="file-1"
          blockId="dir-block-1"
          block={mockDirectoryBlock}
        />
      )

      // Toggle should show for bot editors even without agent block
      const toggle = screen.getByTestId('agent-toggle-bot-789')
      expect(toggle).toBeInTheDocument()
      // Should be in OFF state (no agent exists)
      expect(screen.getByText('Inactive')).toBeInTheDocument()
    })
  })
})
